### ISSUE TITLE
Change note line is in an invalid format

### ISSUE THREAD

**Issue by philpott** [CommandersAct/Serverside-events-bridge#1]
https://github.com/TagCommander/Serverside-events-bridge/blob/d0f0c269b72711c95e979b16feefecbee2ff9342/metadata.yaml#L23

changeNotes: Adding support for Facebook custom fields: "Custom Event Id" and "Test Code".

should be

"Adding support for Facebook custom fields: \"Custom Event Id\" and \"Test Code\"."

**Comment by fandreoli** [comment]
Thanks for highlighting this @philpott.
We fixed the line by removing the colon character.
